### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by EhsanVahab** [machinezone/IXWebSocket#116] opened 2019-09-28 10:52 UTC
Hi dear @bsergean 
How can I install IXWebsocket on the windows?
is vcpkg the only way to use IXW on windows?

**Comment by bsergean** [comment] 2019-09-28 16:01
If you are not well versed in building C++ software on Windows, I recommend vcpkg indeed, but the most important thing is getting familiar with CMake.

Take a look at this file, this is how the unittest is built and run on CI
https://github.com/machinezone/IXWebSocket/blob/master/appveyor.yml

You should try to learn how to user CMake to generate your project files. I assume you'll use Visual Studio.
All the steps needed should be to generate a project file, by running CMake.

**Comment by EhsanVahab** [comment] 2019-09-29 10:18
I tried to build it by VS but I faced the following error:
_**can not open include file unistd.h**_
I know that there's no unistd.h header file on windows c++
I've surfed on the net for the unistd.h on the windows. it seems there's nothing for to be equivalent.
any solution?

**Comment by EhsanVahab** [comment] 2019-09-29 13:08
it's solved by adding the following code to the zconf.h of zlib library
```
#ifdef _WIN32
#include <io.h>
#else
#include <unistd.h>
#endif 
```
now I face another error 
 _**C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(769): error C2679: binary '+=': no operator fou
nd which takes a right-hand operand of type 'const std::chrono::duration<double,std::milli>' (or there is no acceptable
 conversion) (compiling source file D:\Project\Requirements\IXWebSocket
-master\ixwebsocket\IXWebSocket.cpp)**_

**Comment by bsergean** [comment] 2019-09-29 16:28
Make sure that Visual Studio is set to C++11 mode.

**Comment by EhsanVahab** [comment] 2019-09-30 11:46
my visual studio was 2015 update 1. after I updated to version 3 the problem was solved.
now I have ixwebsocket.lib in Release folder but where's the location of include files?

**Comment by bsergean** [comment] 2019-09-30 14:09
install(TARGETS ixwebsocket
        ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
        PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_PREFIX}/include/ixwebsocket/
)

Include files should be installed next to the libs.

**Comment by EhsanVahab** [comment] 2019-10-01 09:03
I install it successfully but when I include the header file and link to the libwebsocket.lib I get the following error
`Error	LNK2001	unresolved external symbol __imp__closesocket@4	HelloCapture	D:\Project\ixwebsocket.lib(IXSocket.obj)`

I mention that my version of visual studio is 2015 with update 3.
is there any other file that must be included or linked to my project?

**Comment by bsergean** [comment] 2019-10-01 14:46
Sorry I cannot help much. Can you make a pull request where you add your vcproj project files with a minimal C++ project to reproduce the errors, or steps to do so ?

Those errors don't ring a bell, and CI works fine on Windows at this point.

**Comment by EhsanVahab** [comment] 2019-10-02 08:22
I've normally created an empty visual studio c++ project.
then I've include the path `${CMAKE_INSTALL_PREFIX}/include/ixwebsocket/ ` and linked `${CMAKE_INSTALL_PREFIX}/lib`
so when I use the following codes I get unresolved symbol error:
```
#include <IXWebSocket.h>
#include <IXNetSystem.h>
#include <iostream>
#include <windows.h>
int main() {

	ix::initNetSystem();
	ix::WebSocket webSocket;
}
```

**Comment by bsergean** [comment] 2019-10-02 22:38
I think you should read about cmake and use cmake to generate your project file. There is continous integration that does that (for the ws script + the unittest), and there are no such linking errors.

**Comment by bsergean** [comment] 2019-10-03 14:46
I tried to build without SSL and everything still works. Still not sure what your problem is.

**Comment by bsergean** [comment] 2019-10-03 18:07
I tried this morning to build with Visual Studio 2015 and the spdlog dependency (only in unittest and command line tool) does not build with it, in 32-bit mode. Looks like visual studio has a problem with std::atomic.

See here -> https://ci.appveyor.com/project/bsergean/ixwebsocket/builds/27860881

I can't get to build for 64 bits, so I'm going to close this ticket.

**Closed by bsergean** 2019-10-03 18:07 UTC

**Comment by EhsanVahab** [comment] 2019-10-03 18:10
> 
> 
> I tried this morning to build with Visual Studio 2015 and the spdlog dependency (only in unittest and command line tool) does not build with it, in 32-bit mode. Looks like visual studio has a problem with std::atomic.
> 
> See here -> https://ci.appveyor.com/project/bsergean/ixwebsocket/builds/27860881
> 
> I can't get to build for 64 bits, so I'm going to close this ticket.

you mean that it's not possible to use IXWebsocket in visual studio win 2 projects?

**Comment by bsergean** [comment] 2019-10-03 18:11
The code compiles and the unittest works with Visual Studio 2017.

I am not a Visual Studio expert so you'll have to research this problem yourself.

**Comment by EhsanVahab** [comment] 2019-10-07 13:42
I find the solution.
the "ws2_32.lib" has to be linked in the project.
just do it.

**Comment by bsergean** [comment] 2019-10-07 15:58
Glad that you found it. If you look at the CMakeLists it has this expression to add wsock32 and ws2_32 as linked libraries.

if (WIN32)
  target_link_libraries(ixwebsocket wsock32 ws2_32)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)
endif()
